version: '3'
services:
  app:
    build: ./Prompt-Management
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    build: ./Prompt-Management-Server
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis-data/dump.rdb:/data/dump.rdb

volumes:
  redis-data:
