version: '3'
services:
  app:
    build: ./my-app
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
